### ISSUE TITLE
Blank map on test branch w/ google.services#v22

### ISSUE THREAD

**Issue by lakano** [wf9a5m75/phonegap-googlemaps-plugin#445]
Hello !

Under the master branch, I see the map. When I try to create the same project, with test branch and google.services#v22, I have a blank map.

For information, my first try can't build, I have found a solution in another ticket to remove the folder : ./platforms/android/com.google.playservices/app-google-play-services_lib/bin/res/crunch/ 

After that, I can run it, and the MAP_READY event is fired, but the map is blank ( and all others HTML element inside the #map-canvas div are correctly shown )

There is no console error. 
I have copied my master branch config.xml file ( so it's the same widget ID, and this is not a KEY problem )

Do you have any idea ?
Thanks a lots !

**Comment by wf9a5m75** [comment]
Did you check logcat error also?

**Comment by lakano** [comment]
In logcat ( adb logcat *:S CordovaLog:D ) I see this line : 
I/CordovaLog( 1469): This app uses phonegap-googlemaps-plugin version 1.2.4

Is the #test branch shouldn't said 1.2.5 ?

**Comment by wf9a5m75** [comment]
I merged the latest code into the master branch last night.
Try to use the master branch with Google Play Services v23.

**Comment by lakano** [comment]
Hello,
I still have the map blank, but this time I haven't build problem.
And in the logcat :
```
I/CordovaLog(32075): This app uses phonegap-googlemaps-plugin version 1.2.5
I/CordovaLog(32075): phonegap-googlemaps-plugin version 1.2.4 is available.
```

Any idea ? :-/

**Comment by wf9a5m75** [comment]
Too less information. That message just outputs the version numbers.

Could you show me **the whole build error log**?

**Comment by lakano** [comment]
I don't known the reason, but today, without any change, this works ! :-/
