### ISSUE TITLE
Issue using Test Branch (No map options, no markers and no animate camera)

### ISSUE THREAD

**Issue by brunodb3** [wf9a5m75/phonegap-googlemaps-plugin#448]
I have implemented the plugin successfully using the Master Branch, but i want to be able to use the Marker Animations. So i did the following to my Ionic Project:

$> cordova plugin rm plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=.......

But now, none of my functions using the map works. I am using AddMarkers, AnimateCamera, and the GetMyLocation, as well as setting custom MapOptions. On Master it works just fine, but on Test, it just gives me the Map with no Controls (i was using them before) and doesn't load my markers or animates the camera.

It is my first time posting on GitHub, so sorry for anything...

**Comment by wf9a5m75** [comment]
I merged the test branch code into the master branch last night. It means the same code.

**Comment by brunodb3** [comment]
So the animations will work on Master now?

**Comment by brunodb3** [comment]
I installed the plugin using the Master branch now, and the issue is still there...

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/phonegap-googlemaps-plugin/blob/master/www/googlemaps-cdv-plugin.js#L877

**Comment by brunodb3** [comment]
What i have is this:

            var mapOptions = {
                mapType: plugin.google.maps.MapTypeId.ROADMAP,
                controls: {
                    compass: true,
                    myLocationButton: true
                },
                gestures: {
                    scroll: true,
                    tilt: true,
                    rotate: true,
                    zoom: true
                }
            };

            root.map = plugin.google.maps.Map.getMap(mapDiv);

            root.map.setOptions(mapOptions);

In this case, root is because i am setting the map as a $rootScope variable (global). What happens is that i set "compass" and "myLocationButton" to true, but neither are showing on the map itself... Also, when i call:
                    root.map.animateCamera({
                        'target': deviceLocation.latLng, // This is from the map.getMyLocation
                        'tilt': 45,
                        'zoom': 16,
                        'bearing': 0,
                        'duration': 1200
                    });

It doesn't animate the camera. It only shows the map and does nothing.

**Comment by wf9a5m75** [comment]
Why don't you just pass the mapOptions to map.getMap();

```
var map = plugin.google.maps.Map.getMap(mapDiv, mapOptions)
```

And you have to wait the MAP_READY event before calling any statement.

**Comment by brunodb3** [comment]
I will try and get back to you, but i don't think it will solve my problem, as it worked before with another version of the plugin...

**Comment by brunodb3** [comment]
I don't know why, but it worked. But now my markers doesn't show my custom icon, and also, i noticed that if i change the "styles" property of the markers, (the color one), they change colors... Like so:

                                    styles: {
                                        'color': 'red' // Will give me a Red Marker
                                        'color': 'blue' // Will give me a Blue Marker
                                    }

Was that supposed to happen?

**Comment by wf9a5m75** [comment]
In the next version, you can change the icon color, but it seems that might be bug.

https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/196

**Comment by brunodb3** [comment]
Okay Masashi, i got it working by doing the marker.setIcon after the marker was created (it shows the default marker first, and then changes, but that's how i got it to work...). Thanks for your awesome and fast support :+1:

**Comment by wf9a5m75** [comment]
:)
